[package]
name = "nhl_stats"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0.219"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
indexmap = { version = "2", features = ["serde"] }